home:
    pattern:  /
    defaults: { _controller: TigerBundle:Default:index }

rachel:
    pattern:  /rachel
    defaults: { _controller: TigerBundle:Rachel/Index:index }

slideshow:
    pattern:  /rachel/slideshow
    defaults: { _controller: TigerBundle:Rachel/Portfolio:slideshow }

app_password:
    pattern:  /downloadApp
    defaults: { _controller: TigerBundle:Rachel/Index:checkPassword }

app_download:
    pattern:  /download
    defaults: { _controller: TigerBundle:Rachel/Index:Download }

contact:
    pattern:  /contact
    defaults: { _controller: TigerBundle:Default:contact }

imaginet:
    pattern:  /imaginet
    defaults: { _controller: TigerBundle:Imaginet/Index:index }

imaginet_info:
    pattern:  /imaginet/info
    defaults: { _controller: TigerBundle:Imaginet/Index:info }