home:
    pattern:  /
    defaults: { _controller: TigerBundle:Default:index }

rachel:
    pattern:  /rachel
    defaults: { _controller: TigerBundle:Rachel/Index:index }

app_password:
    pattern:  /downloadApp
    defaults: { _controller: TigerBundle:Rachel/Index:checkPassword }

app_download:
    pattern:  /download
    defaults: { _controller: TigerBundle:Rachel/Index:Download }

contact:
    pattern:  /contact
    defaults: { _controller: TigerBundle:Default:contact }